baseURL: 'https://gptjddldi.github.io'
languageCode: 'en-us'
title: 'gptjddldi'
theme: 'PaperMod'

enableRobotsTXT: true

googleAnalytics: G-HH9Y7JQXT7


params:
  defaultTheme: 'light'
  ShowToc: true
  homeInfoParams:
      Title: gptjdlddi
      Content: 🏄‍♂️
  socialIcons:
    - name: github
      url: 'https://github.com/gptjddldi'
  comments: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  analytics:
    google:
      SiteVerification: 'qEWr-0TVYw3dT15GiETFmAPsNbhSxnk-xya_mHdUIp4'

menu:
  main:
    - identifier: archives
      name: Archives
      url: /archives
      weight: 10

taxonomies:
  category: categories
  series: series
  tag: tags

