baseURL: 'https://gptjddldi.github.io'
languageCode: 'en-us'
title: 'gptjddldi'
theme: 'PaperMod'

enableRobotsTXT: true

googleAnalytics: G-HH9Y7JQXT7
params:
  analytics:
      google:
        SiteVerificationTag: RZ17MSRZ2G